### ISSUE TITLE
Provide fallback if stream / station server is offline

### ISSUE THREAD

**Issue by Trikolon** [Trikolon/liquidradio#49]
https://sentry.io/pbz/liquidradio/issues/444184634/

```
TypeError: Cannot read property 'id' of undefined
  at None (/bundle.js:15:402024)
  at o.it [as _l] (/bundle.js:1:17256)
  at o.render (/bundle.js:15:401855)
  at o.e._render (/bundle.js:5:10682)
  at o.n (/bundle.js:1:12911)
...
(24 additional frame(s) were not displayed)
```

**Comment by Trikolon** [comment]
https://sentry.io/pbz/liquidradio/issues/444151877/

**Comment by Trikolon** [comment]
https://sentry.io/pbz/liquidradio/issues/444143384/
